### ISSUE TITLE
Remove natnet libraries and replace with download script

### ISSUE THREAD

**Issue by johnny1a679** [jonasauda/VinteR#2]
The provided powershell script downloads the natnet sdk from optitrack. The sdk is needed to communicate with a running instance of motive. This should be used instead of provisioning all dlls. OptiTrack does not provide a license with the natnet sdk.

**Comment by Kr0n0s1011** [comment]
So far i have provided instructions to get the NatNet SDK from optitrack manually. This is due to the fact, that the links and file locations changed in the last year. If the website gets changed again the script would break and would need to be patched.
